ethcore/parity-dapps-status

client/actions/modify-mining.js
client/components/EditableInput/index.js
client/components/EditableInput/style.css
client/components/Status/index.js
client/components/Status/style.css
client/index.js
client/middleware/user-web3-interactions.js

1. Where do u want to put css utils like .relative?
2. where do we get extra data default? or we just hard code it?

add reset extra data

---

client/actions/rpc.js
client/components/Rpc/index.js
client/components/Rpc/style.css
client/data/rpc.json
client/middleware/localstorage.js
client/reducers/rpc.js

didn't add styling yet since u r playing with the gui 
so disregard the ugliness

Reset rpc calls

---

client/components/EditableValue/index.js
client/components/EditableValue/styles.css
client/components/Footer/styles.css
client/components/MiningSettings/index.js
client/components/MiningSettings/style.css
client/components/Status/index.js
client/components/Value/styles.css

Resetting to default is now part of EditableValue component.

---

client/components/EditableValue/index.js

And focusing when using pencil icon.
Closes #26

Opening edit when clicking EditableValue

---

client/components/Header/index.js
client/components/Header/styles.css
client/containers/AccountsPage/index.js
client/containers/AppListPage/index.js
client/containers/DebugPage/index.js
client/containers/RpcPage/index.js
client/containers/StatusPage/index.js

add header warnings display

---

.travis.yml

chore - increase travis sleep before running integration tests

---

webpack.config.js

merging since master is broken

webpack font load hotfix

---

client/provider/rpc-provider.js

status - handle rlp errors

---

package.json

install missing dependency

---

client/components/RpcCalls/index.js
client/components/RpcCalls/style.css
client/provider/dom-provider.js
client/provider/rpc-provider.js

Rpc calls visual fixes

---

client/data/rpc.json
package.json
rpc-docs/index.js

add trace api

---

client/components/Header/index.js
client/provider/web3-provider.js
client/provider/web3-provider.spec.js

Handling disconnected state better.

---

client/provider/rpc-provider.js

handle rpc formatters exceptions

---

client/actions/logger.js
client/components/Footer/index.js
client/components/Footer/styles.css
client/components/Header/index.js
client/components/Header/styles.css
client/containers/AccountsPage/index.js
client/containers/AppListPage/index.js
client/containers/DebugPage/index.js
client/containers/RpcPage/index.js
client/containers/StatusPage/index.js
client/middleware/logger.js
client/middleware/logger.spec.js
client/reducers/index.js
client/reducers/logger.js

resolves #65 
*note* - implemented only in status page
need to implement in rest of pages
@tomusdrw  what do u say about letting header/footer handle it's state instead of passing props?
at the moment every change we make on header we need to implement it on all pages

prettify logging toggle

---

client/components/RpcDocs/index.js
client/provider/vendor-provider.js

autocomplete - make non case sensitive

---

client/actions/toastr.js
client/components/ToastrContainer/index.js
client/components/ToastrContainer/styles.css
client/middleware/rpc.js
client/middleware/toastr.js
client/middleware/toastr.spec.js
client/provider/error-provider.js
client/provider/error-provider.spec.js

1. I'm not so sure about error provider ...
usually providers shouldn't be aware of each other
tho it might be useful (and DRY) to be able to delegate toasting of errors like that
since it something that will probably happen quite often
2. build currently fails on lint
will pass once #86 is merged

Rpc formatters exceptions continue

---

client/actions/status.js
client/components/EditableValue/index.js
client/components/EditableValue/styles.css
client/components/MiningSettings/index.js
client/components/Status/index.js
client/provider/web3-provider.js
client/reducers/status.js

resolves #33 
todo - update e2e tests accordingly
what u say about this implementation?

add selectable options for modifying author

---

client/actions/debug.js
client/components/Debug/index.js
client/components/Debug/style.css
client/containers/DebugPage/index.js
client/provider/web3-provider.js
client/reducers/debug.js

enhance dev logs

---

client/index.js
client/middleware/index.js

Using single web3 instance. Closes #113

Single web3 instance

---

client/data/rpc.json
rpc-docs/index.js

fix rpc docs and generator

---

client/components/ScrollTopButton/index.js

fix scroll top button event listener

---

client/actions/mining.js
client/components/EditableValue/index.js
client/components/MiningSettings/decodeExtraData.js
client/components/MiningSettings/decodeExtraData.spec.js
client/components/MiningSettings/index.js
client/data/rpc.json
client/provider/rpc-provider.js
client/provider/rpc-provider.spec.js
client/provider/web3-ethcore-provider.js
client/provider/web3-provider.js
client/reducers/mining.js
rpc-docs/index.js
test/e2e/status-page.js
test/mocked-responses.json

On ice for now - requires additional fix in ethcore/parity to work.
Requires: https://github.com/ethcore/parity/pull/1060
Resolves: #90 #91 #92

Fixing extra data

---

client/components-compositors/Animated/children.js
client/components-compositors/Animated/index.js
client/components-compositors/Animated/style.css
client/components/Calls/index.js
client/components/Debug/index.js
client/components/RpcCalls/index.js
client/components/RpcDocs/index.js
client/components/Status/index.js
client/util/react.js
package.json

I really like [this](http://angular.github.io/angular-phonecat/step-12/app/#/phones) view animation 
(click on any item to c it in action)
if we want to achieve that without fancy hacks, I think we'll need to move header and footer to app container
closes #121

add animations to nodes/children

---

client/components/Markdown/index.js
client/components/Markdown/style.css
client/components/RpcCalls/index.js
client/components/RpcDocs/index.js
client/data/rpc.json
client/provider/rpc-provider.js
client/util/index.js
client/util/rpc-md.js
rpc-docs/add-formatters.js
rpc-docs/custom-functions.js
rpc-docs/format.js
rpc-docs/index.js

Gen object fix

---

client/routes.js

https://github.com/reactjs/react-router/issues/1967

Disabling state in url

---

package.json

add author and repo to package json

---

.eslintrc.json
client/components/Header/Header.js
client/components/JsonEditor/JsonEditor.js
client/components/Markdown/Markdown.js
client/components/MiningSettings/MiningSettings.js
client/components/MiningSettings/decodeExtraData.js
client/components/MiningSettings/decodeExtraData.spec.js
client/components/MiningSettings/numberFromString.spec.js
client/components/MuiThemeProvider/MuiThemeProvider.js
client/components/Response/Response.js
client/components/RpcCalls/RpcCalls.js
client/components/RpcDocs/RpcDocs.js
client/components/ScrollTopButton/ScrollTopButton.js
client/components/Status/Status.js
client/containers/DebugPage/DebugPage.js
client/containers/RpcPage/RpcPage.js
client/containers/StatusPage/StatusPage.js
client/middleware/localstorage.js
client/middleware/localstorage.spec.js
client/middleware/logger.spec.js
client/middleware/rpc.js
client/middleware/user-web3-interactions.js
client/provider/web3-provider.js
client/provider/web3-provider.spec.js
client/reducers/rpc.js
client/test/index.js

Introduce curly spacing rules and implement it, as discussed.
`const {blah, bleh} = this.state` -> `const { blah, bleh } = this.state`
Applies to imports, object definitions & variable destructuring.

object-curly-spacing rule

---

client/components/EditableValue/EditableValue.js
client/components/Markdown/Markdown.js
client/components/RpcCalls/RpcCalls.js
client/components/ScrollTopButton/ScrollTopButton.js
client/provider/web3-provider.js

move all state definitions out of the constructor and into the class body

state as part of class body

---

package.json
test/apply-babel.js
test/mocha.opts

fix mocha test watch

---

client/components/Call/Call.js

fix call params display

---

client/data/rpc.json
rpc-docs/custom-functions.js
test/e2e/rpc-page.js

eth_ -> personal_
